// GENERATED by tools/train-pooled.mjs — do not edit by hand.
//
// One logistic regression per timeframe, fitted across every coin at once. The
// features are the same ATR-normalised vector buildFeatures() produces, so a row
// from one coin is comparable with a row from another and the model learns market
// behaviour rather than a ticker.
//
// Trained strictly on the first 55% of each series, which ends before the first
// forecast the accuracy harness measures — so the published accuracy is never
// measured on data this model was fitted to.
export const POOLED = {
  "15m": {
    "w": [
      -0.082736,
      0.012135,
      -0.108214,
      -0.006819,
      0.041351,
      -0.033672,
      0.339391,
      -0.013312,
      0.233854,
      -0.053516,
      -0.134121,
      -0.240105,
      0.48896,
      0.033252,
      0.03683,
      0.123806,
      -0.407989,
      0.053043,
      0.129424,
      0.109167,
      -0.023035,
      -0.00893,
      -0.473182,
      0.055817
    ],
    "rows": 25584,
    "series": 12,
    "inSample": 55.83,
    "upRate": 51.34
  },
  "1h": {
    "w": [
      0.031746,
      -0.046885,
      0.134234,
      0.113742,
      -0.178914,
      -0.287109,
      -0.160177,
      -0.01933,
      0.265836,
      -0.059209,
      0.015001,
      -0.70698,
      0.256897,
      0.108338,
      -0.003282,
      -0.612124,
      0.434832,
      -0.071442,
      -0.386638,
      -0.064753,
      0.017124,
      -0.169066,
      -0.076034,
      -0.017344
    ],
    "rows": 25536,
    "series": 12,
    "inSample": 55.81,
    "upRate": 48.2
  },
  "4h": {
    "w": [
      0.048348,
      -0.062721,
      -0.012447,
      -0.149116,
      0.009005,
      -0.13697,
      -0.079143,
      -0.046123,
      -0.032592,
      0.091716,
      -0.028371,
      -0.651792,
      0.1718,
      -0.075978,
      -0.01284,
      0.321665,
      0.683472,
      0.167386,
      -0.034165,
      0.019587,
      -0.18859,
      -0.087084,
      0.662426,
      0.04879
    ],
    "rows": 22308,
    "series": 12,
    "inSample": 54.32,
    "upRate": 49.48
  },
  "1d": {
    "w": [
      0.017418,
      0.115746,
      -0.055303,
      0.019174,
      0.240868,
      -0.388618,
      -0.2628,
      0.188211,
      -0.420044,
      0.263163,
      0.122314,
      -0.199383,
      -0.040052,
      0.149676,
      0.115402,
      -0.30281,
      -0.255729,
      0.183466,
      0.11997,
      -0.024826,
      0.084611,
      0.092588,
      0.648928,
      0.014267
    ],
    "rows": 13706,
    "series": 12,
    "inSample": 54.74,
    "upRate": 50.91
  }
};

const clip = (v, a = -30, b = 30) => (Number.isFinite(v) ? Math.min(b, Math.max(a, v)) : 0);

/** P(up) from the pooled model for one feature row, or null if untrained here. */
export function pooledProb(interval, features) {
  const m = POOLED[interval];
  if (!m || !features) return null;
  const w = m.w;
  if (features.length + 1 !== w.length) return null;
  let z = w[w.length - 1];
  for (let j = 0; j < features.length; j++) z += w[j] * features[j];
  return 1 / (1 + Math.exp(-clip(z)));
}
