// GENERATED by tools/train-pooled.mjs — do not edit by hand.
//
// One logistic regression per timeframe, fitted across every coin at once. The
// features are the same ATR-normalised vector buildFeatures() produces, so a row
// from one coin is comparable with a row from another and the model learns market
// behaviour rather than a ticker.
//
// Trained strictly on the first 55% of each series, which ends before the first
// forecast the accuracy harness measures — so the published accuracy is never
// measured on data this model was fitted to.
export const POOLED = {
  "1m": {
    "w": [
      -0.044273,
      0.015889,
      0.05412,
      0.00343,
      -0.135473,
      0.212433,
      -0.643717,
      0.168754,
      0.122383,
      0.037515,
      -0.119953,
      0.345058,
      -0.202379,
      -0.023843,
      -0.015699,
      0.043804,
      -0.124418,
      -0.053749,
      0.090183,
      -0.049131,
      0.230138,
      -0.067926,
      -0.720631,
      -0.177954
    ],
    "rows": 25500,
    "series": 12,
    "inSample": 57.1,
    "upRate": 46.66
  },
  "5m": {
    "w": [
      -0.066342,
      -0.014672,
      0.096099,
      0.048818,
      0.150638,
      0.509868,
      -0.070007,
      -0.259237,
      -0.759575,
      -0.304791,
      -0.070526,
      -0.058198,
      0.099322,
      -0.32245,
      -0.014203,
      -0.033012,
      -0.358983,
      0.194451,
      0.410955,
      0.013397,
      -0.06911,
      -0.181352,
      -0.022778,
      0.183813
    ],
    "rows": 25536,
    "series": 12,
    "inSample": 55.81,
    "upRate": 52
  },
  "15m": {
    "w": [
      -0.082806,
      0.042662,
      -0.12184,
      0.037343,
      0.056187,
      -0.106384,
      0.501074,
      -0.086483,
      0.296288,
      0.004193,
      -0.124654,
      -0.157645,
      0.410264,
      -0.046879,
      0.041749,
      0.073061,
      -0.495089,
      0.03574,
      0.207977,
      0.097733,
      -0.016712,
      -0.076474,
      -0.275691,
      0.085259
    ],
    "rows": 25584,
    "series": 12,
    "inSample": 56.52,
    "upRate": 51.61
  },
  "1h": {
    "w": [
      0.040758,
      -0.060787,
      0.134774,
      0.093437,
      -0.207438,
      -0.311861,
      -0.167681,
      -0.044237,
      0.236485,
      -0.028586,
      -0.02101,
      -0.682827,
      0.209921,
      0.063106,
      -0.005462,
      -0.714338,
      0.581887,
      -0.022631,
      -0.336114,
      -0.062979,
      0.014642,
      -0.201564,
      0.094302,
      -0.000775
    ],
    "rows": 25536,
    "series": 12,
    "inSample": 55.93,
    "upRate": 48.35
  },
  "4h": {
    "w": [
      0.045645,
      -0.073317,
      -0.006436,
      -0.166654,
      0.035197,
      -0.145741,
      -0.100377,
      -0.051393,
      -0.037874,
      0.079033,
      -0.043634,
      -0.620415,
      0.11355,
      -0.091959,
      -0.001203,
      0.313344,
      0.776972,
      0.190967,
      -0.013086,
      0.027754,
      -0.209346,
      -0.084197,
      0.628506,
      0.059335
    ],
    "rows": 22308,
    "series": 12,
    "inSample": 54.43,
    "upRate": 49.57
  },
  "1d": {
    "w": [
      0.017982,
      0.115917,
      -0.053704,
      0.028102,
      0.243171,
      -0.39093,
      -0.273344,
      0.192121,
      -0.423538,
      0.261978,
      0.119355,
      -0.20245,
      -0.03926,
      0.142067,
      0.116595,
      -0.289204,
      -0.252945,
      0.183891,
      0.101981,
      -0.031117,
      0.082821,
      0.090604,
      0.654072,
      0.015049
    ],
    "rows": 13705,
    "series": 12,
    "inSample": 54.78,
    "upRate": 50.92
  }
};

const clip = (v, a = -30, b = 30) => (Number.isFinite(v) ? Math.min(b, Math.max(a, v)) : 0);

/** P(up) from the pooled model for one feature row, or null if untrained here. */
export function pooledProb(interval, features) {
  const m = POOLED[interval];
  if (!m || !features) return null;
  const w = m.w;
  if (features.length + 1 !== w.length) return null;
  let z = w[w.length - 1];
  for (let j = 0; j < features.length; j++) z += w[j] * features[j];
  return 1 / (1 + Math.exp(-clip(z)));
}
