// Trains one cross-coin model per timeframe, offline.
//
// Why: every model inside forecast() is trained on a single coin's own history —
// roughly two thousand usable rows. That is thin, which is why the per-coin
// weights are noisy and why stacking overfitted when it was tried. The features
// in buildFeatures() are all divided by ATR, so they carry no price scale and a
// row from SOL means the same thing as a row from BTC. Pooling twelve coins
// gives ~20k rows to fit on instead.
//
// Honesty: it trains ONLY on the first part of every series, ending well before
// the first origin the accuracy harness ever tests, so the published number is
// never measured on data the model saw. See TRAIN_FRACTION below.
//
// usage: node tools/train-pooled.mjs /tmp/klines.json js/lib/pooled.js
import fs from 'node:fs';
import { buildFeatures } from '../js/lib/predict.js';

const [, , file, outFile = 'js/lib/pooled.js'] = process.argv;
const data = JSON.parse(fs.readFileSync(file, 'utf8'));
// The app offers ten timeframes and only four had a model, so a forecast on the
// 1m or 5m chart fell back to the per-coin models alone. These horizons match
// the ones the coin page uses, so the model is fitted to the question actually
// being asked.
const HMAP = { '1m': 15, '5m': 12, '15m': 8, '1h': 12, '4h': 6, '1d': 7 };

// evaluate-engine.mjs starts testing at max(1500, 60% of the series). Training
// stops before 55% minus a horizon, so no training row can share a candle with
// any tested forecast.
const TRAIN_FRACTION = 0.55;

const clip = (v, a = -6, b = 6) => (Number.isFinite(v) ? Math.min(b, Math.max(a, v)) : 0);
const sigmoid = (z) => 1 / (1 + Math.exp(-clip(z, -30, 30)));

/** Logistic regression, L2 on the slopes, plain gradient descent. */
function fit(rows, ys, { l2 = 6, iters = 900, lr = 0.9 } = {}) {
  const d = rows[0].length;
  const w = new Array(d).fill(0);
  for (let it = 0; it < iters; it++) {
    const g = new Array(d).fill(0);
    for (let r = 0; r < rows.length; r++) {
      const x = rows[r];
      let z = 0;
      for (let j = 0; j < d; j++) z += w[j] * x[j];
      const err = sigmoid(z) - ys[r];
      for (let j = 0; j < d; j++) g[j] += err * x[j];
    }
    for (let j = 0; j < d - 1; j++) g[j] += l2 * w[j]; // last column is the intercept
    for (let j = 0; j < d; j++) w[j] -= (lr / rows.length) * g[j];
  }
  return w;
}

const out = {};
for (const interval of Object.keys(HMAP)) {
  const H = HMAP[interval];
  const rows = [];
  const ys = [];
  let series = 0;
  for (const key of Object.keys(data)) {
    if (key.split(':')[1] !== interval) continue;
    const c = data[key].map(([t, o, h, l, cc, v]) => ({ t, o, h, l, c: cc, v }));
    if (c.length < 500) continue;
    series++;
    const feats = buildFeatures(c);
    const stop = Math.floor(c.length * TRAIN_FRACTION) - H;
    for (let i = 60; i < stop; i++) {
      if (!feats[i]) continue;
      rows.push([...feats[i], 1]);
      ys.push(c[i + H].c > c[i].c ? 1 : 0);
    }
  }
  if (rows.length < 500) { console.error(interval, 'not enough rows'); continue; }

  const w = fit(rows, ys);

  // in-sample sanity only — the real number comes from evaluate-engine
  let hit = 0;
  for (let r = 0; r < rows.length; r++) {
    let z = 0;
    for (let j = 0; j < w.length; j++) z += w[j] * rows[r][j];
    if ((sigmoid(z) >= 0.5 ? 1 : 0) === ys[r]) hit++;
  }
  const upRate = ys.reduce((a, b) => a + b, 0) / ys.length;
  out[interval] = { w: w.map((v) => +v.toFixed(6)), rows: rows.length, series, inSample: +(hit / rows.length * 100).toFixed(2), upRate: +(upRate * 100).toFixed(2) };
  console.error(`${interval}: ${rows.length} rows from ${series} coins, in-sample ${out[interval].inSample}% (base rate ${out[interval].upRate}%)`);
}

const body = `// GENERATED by tools/train-pooled.mjs — do not edit by hand.
//
// One logistic regression per timeframe, fitted across every coin at once. The
// features are the same ATR-normalised vector buildFeatures() produces, so a row
// from one coin is comparable with a row from another and the model learns market
// behaviour rather than a ticker.
//
// Trained strictly on the first ${Math.round(TRAIN_FRACTION * 100)}% of each series, which ends before the first
// forecast the accuracy harness measures — so the published accuracy is never
// measured on data this model was fitted to.
export const POOLED = ${JSON.stringify(out, null, 2)};

const clip = (v, a = -30, b = 30) => (Number.isFinite(v) ? Math.min(b, Math.max(a, v)) : 0);

/** P(up) from the pooled model for one feature row, or null if untrained here. */
export function pooledProb(interval, features) {
  const m = POOLED[interval];
  if (!m || !features) return null;
  const w = m.w;
  if (features.length + 1 !== w.length) return null;
  let z = w[w.length - 1];
  for (let j = 0; j < features.length; j++) z += w[j] * features[j];
  return 1 / (1 + Math.exp(-clip(z)));
}
`;
fs.writeFileSync(outFile, body);
console.error('wrote', outFile);
